package com.jsict.biz.dao.impl;

import org.springframework.stereotype.Repository;
import com.jsict.framework.core.dao.hibernate.GenericHibernateDaoImpl;
import com.jsict.biz.dao.CodeDao;
import com.jsict.biz.model.Code;

/**
* Auto-Generated by UDP Generator
*/
@Repository
public class CodeDaoImpl extends GenericHibernateDaoImpl<Code, String> implements CodeDao {

}
