package com.jsict.biz.dao.impl;

import org.springframework.stereotype.Repository;
import com.jsict.framework.core.dao.hibernate.GenericHibernateDaoImpl;
import com.jsict.biz.dao.DepartmentDao;
import com.jsict.biz.model.Department;

/**
* Auto-Generated by UDP Generator
*/
@Repository
public class DepartmentDaoImpl extends GenericHibernateDaoImpl<Department, String> implements DepartmentDao {

}
