package com.jsict.biz.dao.impl;

import org.springframework.stereotype.Repository;
import com.jsict.framework.core.dao.hibernate.GenericHibernateDaoImpl;
import com.jsict.biz.dao.ModuleDao;
import com.jsict.biz.model.Module;

/**
* Auto-Generated by UDP Generator
*/
@Repository
public class ModuleDaoImpl extends GenericHibernateDaoImpl<Module, String> implements ModuleDao {

}
