package com.jsict.biz.dao.impl;

import org.springframework.stereotype.Repository;
import com.jsict.framework.core.dao.hibernate.GenericHibernateDaoImpl;
import com.jsict.biz.dao.MultiCodeDao;
import com.jsict.biz.model.MultiCode;

/**
* Auto-Generated by UDP Generator
*/
@Repository
public class MultiCodeDaoImpl extends GenericHibernateDaoImpl<MultiCode, String> implements MultiCodeDao {

}
