package com.jsict.biz.dao.impl;

import org.springframework.stereotype.Repository;
import com.jsict.framework.core.dao.hibernate.GenericHibernateDaoImpl;
import com.jsict.biz.dao.RoleDao;
import com.jsict.biz.model.Role;

/**
* Auto-Generated by UDP Generator
*/
@Repository
public class RoleDaoImpl extends GenericHibernateDaoImpl<Role, String> implements RoleDao {

}
