package com.jsict.biz.dao.impl;


import com.jsict.biz.model.SensitiveWords;
import org.springframework.stereotype.Repository;
import com.jsict.framework.core.dao.hibernate.GenericHibernateDaoImpl;
import com.jsict.biz.dao.SensitiveWordsDao;

/**
* Auto-Generated by UDP Generator
*/
@Repository
public class SensitiveWordsDaoImpl extends GenericHibernateDaoImpl<SensitiveWords, String> implements SensitiveWordsDao {

}
