package com.jsict.biz.dao.impl;

import org.springframework.stereotype.Repository;
import com.jsict.framework.core.dao.hibernate.GenericHibernateDaoImpl;
import com.jsict.biz.dao.UdpPointPermissionDao;
import com.jsict.biz.model.UdpPointPermission;

/**
* Auto-Generated by UDP Generator
*/
@Repository
public class UdpPointPermissionDaoImpl extends GenericHibernateDaoImpl<UdpPointPermission, String> implements UdpPointPermissionDao {

/**
 * 示例代码
 * @Override
 * public UdpPointPermission save(UdpPointPermission entity){
 * return super.save(entity);
 * }
 */
}
