package com.jsict.biz.dao.impl;

import com.jsict.biz.dao.WeddingPhotoDao;
import com.jsict.biz.model.WeddingPhoto;
import com.jsict.framework.core.dao.hibernate.GenericHibernateDaoImpl;
import org.springframework.stereotype.Repository;

/**
 * Auto-Generated by UDP Generator
 */
@Repository
public class WeddingPhotoDaoImpl extends GenericHibernateDaoImpl<WeddingPhoto, String> implements WeddingPhotoDao {

}
