package com.jsict.biz.service;

import com.jsict.framework.core.service.GeneriService;
import com.jsict.biz.model.Code;

/**
 * Auto-Generated by UDP Generator
 */
public interface CodeService extends GeneriService<Code, String> {

    /**
     * 生成下层编码
     *
     * @param parentCode
     * @return
     */
    String generateCode(String parentCode);
}
