package com.jsict.biz.service;

import com.jsict.framework.core.model.IDataDictionary;
import com.jsict.framework.core.service.GeneriService;
import com.jsict.biz.model.DataDictionary;

import java.util.List;

/**
 * Auto-Generated by UDP Generator
 */
public interface DataDictionaryService extends GeneriService<DataDictionary, String> {

    /**
     * 查找数据字典
     *
     * @param dictTable
     * @param dictCode
     * @param dictText
     * @return
     */
    List<IDataDictionary> getDictionary(String dictTable, String dictCode, String dictText);
}
