package com.jsict.biz.service;

import com.jsict.framework.core.service.GeneriService;
import com.jsict.biz.model.Department;

import java.util.List;

/**
 * Auto-Generated by UDP Generator
 */
public interface DepartmentService extends GeneriService<Department, String> {

    /**
     * 查找所有部门
     *
     * @return
     */
    List<Department> findAll();
    /**
     * 激活部门
     *
     * @param id
     */
    void enable(String id);

    /**
     * 禁用部门
     *
     * @param id
     */
    void disable(String id);

    /**
     * 查询子部门
     * @param parentDeptId
     * @return
     */
    List<Department> findByParentDeptId(String parentDeptId);

}
