package com.jsict.biz.service;

import com.jsict.framework.core.service.GeneriService;
import com.jsict.biz.model.InformationContent;

/**
 * Auto-Generated by UDP Generator
 */
public interface InformationContentService extends GeneriService<InformationContent, String> {
}
