package com.jsict.biz.service;

import com.jsict.biz.model.Module;
import com.jsict.biz.model.Role;
import com.jsict.biz.model.TreeNode;
import com.jsict.framework.core.service.GeneriService;

import java.util.List;
import java.util.Map;

/**
 * Auto-Generated by UDP Generator
 */
public interface ModuleService extends GeneriService<Module, String> {

    /**
     * 根据角色查找模块
     *
     * @param params
     * @param roles
     * @return
     */
    List<Module> findByRoles(Map<String, Object> params, List<Role> roles);
    /**
     * 根据角色查找模块所有层级
     *
     * @param params
     * @param roles
     * @return
     */
    List<Module> findAllByRoles(Map<String, Object> params, List<Role> roles);

    /**
     * 根据角色查找模块
     *
     * @param params
     * @param roleList
     * @return
     */
    List<Module> findByRoleList(Map<String, Object> params, List<String> roleList);

    /**
     * 查找所有模块
     *
     * @return
     */
    List<Module> findAll();

    /**
     * 获取所有菜单
     *
     * @param isAdmin 是否管理员
     * @param parentRoleId  父层角色ID
     * @param roleId  角色ID
     * @return
     */
    TreeNode getModuleFullTreeForRole(boolean isAdmin, String parentRoleId, String roleId);

    List<Module> getModuleFullTreeByUser(boolean isAdmin,List<Role> roles, Module parentModule);


    /**
     * 获取角色可配置的模块树
     *
     * @param isAdmin 是否管理员
     * @param role  角色
     * @return
     */
    List<TreeNode> getModuleTreeForRole(boolean isAdmin, Role role);

}
