package com.jsict.biz.service;

import com.jsict.framework.core.service.GeneriService;
import com.jsict.biz.model.MultiCode;

import java.util.List;

/**
 * Auto-Generated by UDP Generator
 */
public interface MultiCodeService extends GeneriService<MultiCode, String> {
    List<MultiCode> findAll();

    List<MultiCode> findId(String name);

    boolean findValue(MultiCode multiCode);

    boolean updateValue(MultiCode multiCode);
}
