package com.jsict.biz.service;

import com.jsict.biz.model.MultiCodeValue;
import com.jsict.framework.core.service.GeneriService;

import java.util.List;

/**
 * Auto-Generated by UDP Generator
 */
public interface MultiCodeValueService extends GeneriService<MultiCodeValue, String> {
    List<MultiCodeValue> findAll();

    List<MultiCodeValue> findByParentItemId(String parentItemId);

    boolean findValue(MultiCodeValue multiCodeValue);

    boolean findByUpdate(MultiCodeValue multiCodeValue);

    boolean updateValue(MultiCodeValue multiCodeValue);

    String getCode(MultiCodeValue multiCodeValue);

    List<MultiCodeValue> findValueByCodeId(String codeId);
}
