package com.jsict.biz.service;

import com.jsict.framework.core.service.GeneriService;
import com.jsict.biz.model.SensitiveWords;

import java.util.List;

/**
 * Auto-Generated by UDP Generator
 */
public interface SensitiveWordsService extends GeneriService<SensitiveWords, String> {

    List<SensitiveWords> loadAllWords();
}
