package com.jsict.biz.service;

import com.jsict.biz.model.UdpPointPermission;
import com.jsict.biz.model.User;
import com.jsict.framework.core.service.GeneriService;

import java.util.List;

/**
 * Auto-Generated by UDP Generator
 */
public interface UdpPointPermissionService extends GeneriService<UdpPointPermission, String> {

    List<UdpPointPermission> findByUser(User u);
}
