package com.jsict.biz.service;

import com.jsict.biz.model.WeddingPhoto;
import com.jsict.framework.core.service.GeneriService;

import java.util.List;

/**
 * Auto-Generated by UDP Generator
 */
public interface WeddingPhotoService extends GeneriService<WeddingPhoto, String> {
    String photoSort(List<WeddingPhoto> list);
}
