package com.jsict.biz.service.impl;

import com.jsict.framework.core.service.impl.GeneriServiceImpl;
import com.jsict.biz.model.Code;
import com.jsict.biz.service.CodeService;

import com.jsict.framework.utils.SysConfig;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Auto-Generated by UDP Generator
 */
@Service
public class CodeServiceImpl extends GeneriServiceImpl<Code, String> implements CodeService {

    @Autowired
    private SysConfig sysConfig;

    @Transactional
    @Override
    public String generateCode(String parentCode) {
        Integer codeBits = sysConfig.getConfig().getInt("codeBits");
        Code query = new Code();
        query.setParentCode(parentCode);
        Code code = singleResult(query);
        Integer maxCode = 1;
        if(code!=null){
            maxCode = Integer.valueOf(code.getMaxChildCode());
            maxCode++;
        }else{
            code = new Code();
            code.setParentCode(parentCode);
        }
        StringBuilder sb = new StringBuilder();
        String maxCodeStr = maxCode.toString();
        int codeLength = codeBits - maxCodeStr.length();
        int parentLength = parentCode.length();
        if(parentLength<codeBits)
            codeLength = codeLength - parentLength;
        for( int i = 0; i < codeLength; i++)
            sb.append("0");
        sb.append(maxCodeStr);
        maxCodeStr = sb.toString();
        code.setMaxChildCode(maxCodeStr);
        save(code);
        return parentCode + maxCodeStr;
    }
}
