package com.jsict.biz.service.impl;

import com.jsict.biz.dao.DataDictionaryDao;
import com.jsict.framework.core.dao.annotation.Dictionary;
import com.jsict.framework.core.model.IDataDictionary;
import com.jsict.framework.core.service.impl.GeneriServiceImpl;
import com.jsict.biz.model.DataDictionary;
import com.jsict.biz.service.DataDictionaryService;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * Auto-Generated by UDP Generator
 */
@Service
public class DataDictionaryServiceImpl extends GeneriServiceImpl<DataDictionary, String> implements DataDictionaryService {

    @Transactional(readOnly = true)
    @Override
    public List<IDataDictionary> getDictionary(String dictTable, String dictCode, String dictText) {
        if(Dictionary.DEFAULT_DATA_DICTIONARY.equals(dictTable)){
            return ((DataDictionaryDao)genericDao).getDataDictionary(dictCode);
        }else{
            return ((DataDictionaryDao)genericDao).getDataDictionary(dictTable, dictCode, dictText);
        }
    }
}
