package com.jsict.biz.service.impl;

import com.jsict.framework.core.service.impl.GeneriServiceImpl;
import com.jsict.biz.model.InformationContent;
import com.jsict.biz.service.InformationContentService;

import org.springframework.stereotype.Service;

/**
 * Auto-Generated by UDP Generator
 */
@Service
public class InformationContentServiceImpl extends GeneriServiceImpl<InformationContent, String> implements InformationContentService {

}
