package com.jsict.biz.service.impl;

import com.jsict.biz.dao.WeddingPhotoDao;
import com.jsict.biz.model.DataDictionary;
import com.jsict.biz.model.WeddingPhoto;
import com.jsict.biz.service.DataDictionaryService;
import com.jsict.biz.service.WeddingPhotoService;
import com.jsict.framework.core.service.impl.GeneriServiceImpl;
import org.json.JSONArray;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Auto-Generated by UDP Generator
 */
@Service
public class WeddingPhotoServiceImpl extends GeneriServiceImpl<WeddingPhoto, String> implements WeddingPhotoService {

    @Autowired
    private DataDictionaryService dataDictionaryService;

    /**
     * 照片分类
     * @return
     */
    @Override
    public String photoSort(List<WeddingPhoto> list) {
        DataDictionary dataDictionary = dataDictionaryService.get("40288089703dcbe901703dcf943a0007");
        Set<String> photoSort = new HashSet<>();
        for(WeddingPhoto weddingPhoto : list)
        {
            photoSort.add(weddingPhoto.getPhotoSort().split("\\|")[2]);
        }

        String content = dataDictionary.getContent();
        JSONArray jsonArray = new JSONArray(content);
        JSONArray result = new JSONArray();
        for(int i = 0; i < jsonArray.length(); i++)
        {
            String key = jsonArray.getJSONObject(i).getString("key");
            if(photoSort.contains(key))
            {
                result.put(jsonArray.getJSONObject(i));
            }
        }

        return result.toString();
    }
}