package com.jsict.biz.model;

import com.jsict.framework.core.dao.annotation.LogicDel;
import com.jsict.framework.core.dao.annotation.Monitor;
import com.jsict.framework.core.dao.annotation.MonitorType;
import com.jsict.framework.core.dao.hibernate.EntityOperationListener;
import com.jsict.framework.core.model.BaseEntity;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Table;


/**
 * Auto-Generated by UDP Generator
 */
@Entity
@Table(name = "code")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@EntityListeners(EntityOperationListener.class)
@LogicDel
@Monitor(name = "编码", types = {MonitorType.CREATE, MonitorType.UPDATE, MonitorType.DELETE})
public class Code extends BaseEntity<String> {

    /** 上层编码 */
    @Column(name = "parent_code", length = 80)
    private String parentCode;
    /** 下层最大编码 */
    @Column(name = "max_child_code", length = 30)
    private String maxChildCode;

    public void setParentCode(String parentCode){
        this.parentCode = parentCode;
    }

    public String getParentCode(){
        return this.parentCode;
    }
    public void setMaxChildCode(String maxChildCode){
        this.maxChildCode = maxChildCode;
    }

    public String getMaxChildCode(){
        return this.maxChildCode;
    }
}