package com.jsict.biz.model;

import java.util.Date;

/**
* Auto-Generated by UDP Generator
*/
public class InformationContentQuery extends InformationContent {

        private Date releasedDateStart;

        private Date releasedDateEnd;

        public void setReleasedDateStart(Date releasedDateStart){
            this.releasedDateStart = releasedDateStart;
        }

        public Date getReleasedDateStart(){
            return this.releasedDateStart;
        }

        public void setReleasedDateEnd(Date releasedDateEnd){
        this.releasedDateEnd = releasedDateEnd;
        }

        public Date getReleasedDateEnd(){
        return this.releasedDateEnd;
        }
    }