package com.jsict.biz.model;

import com.jsict.framework.core.dao.annotation.*;
import com.jsict.framework.core.dao.hibernate.EntityOperationListener;
import com.jsict.framework.core.model.BaseEntity;
import org.hibernate.validator.constraints.NotBlank;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Table;


/**
 * 敏感词实体类
 * Auto-Generated by UDP Generator
 */
@Entity
@LogicDel
@Table(name = "sensitive_words")
@EntityListeners(EntityOperationListener.class)
@Monitor(name = "敏感词", types = {MonitorType.CREATE, MonitorType.UPDATE, MonitorType.DELETE})
public class SensitiveWords extends BaseEntity<String> {

    /** 敏感词 */
    @NotBlank(message="敏感词不能为空")
    @Column(name = "words", unique = true, nullable = false)
    private String words;

    public void setWords(String words){
        this.words = words;
    }

    public String getWords(){
        return this.words;
    }
}