package com.jsict.biz.model;

import com.jsict.framework.core.model.BaseEntity;
import com.jsict.framework.core.dao.annotation.LogicDel;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;


/**
 * Auto-Generated by UDP Generator
 */
@LogicDel
@Entity
@Table(name = "udp_point_permission")
public class UdpPointPermission extends BaseEntity<String> {

    /** 功能点名称 */
    @Column(name = "point_name", length = 50)
    private String pointName;
    /** 功能点表达式 */
    @Column(name = "point_expression", length = 100)
    private String pointExpression;

    @ManyToMany(fetch = FetchType.EAGER)
    @Fetch(value = FetchMode.SUBSELECT)
    @JoinTable(name = "point_in_role",
            joinColumns = {
                    @JoinColumn(name = "point_id")
            },
            inverseJoinColumns = {
                    @JoinColumn(name = "role_id")
            }
    )
    private List<Role> roleList = new ArrayList<>();

    public List<Role> getRoleList() {
        return roleList;
    }

    public void setRoleList(List<Role> roleList) {
        this.roleList = roleList;
    }

    public void setPointName(String pointName){
        this.pointName = pointName;
    }

    public String getPointName(){
        return this.pointName;
    }
    public void setPointExpression(String pointExpression){
        this.pointExpression = pointExpression;
    }

    public String getPointExpression(){
        return this.pointExpression;
    }
}