package com.jsict.biz.controller;

import com.jsict.biz.model.User;
import com.jsict.framework.core.controller.AbstractGenericController;
import com.jsict.biz.model.InformationContent;
import com.jsict.biz.model.InformationContentQuery;

import com.jsict.framework.core.controller.CSRFTokenManager;
import com.jsict.framework.core.controller.Response;
import org.apache.shiro.SecurityUtils;
import org.springframework.web.bind.annotation.*;
import org.springframework.stereotype.Controller;

import javax.servlet.http.HttpServletRequest;

/**
 * Auto-Generated by UDP Generator
 */
@Controller
@RequestMapping("information")
public class InformationContentController extends
    AbstractGenericController<InformationContent, String,
    InformationContentQuery> {

    @Override
    @RequestMapping(value = "/save", method = RequestMethod.POST, produces = "application/json")
    @ResponseBody
    public Response save(@ModelAttribute InformationContent entity, @RequestParam(value = CSRFTokenManager.CSRF_PARAM_NAME) String paramToken, HttpServletRequest request) {
        User user = (User)SecurityUtils.getSubject().getPrincipal();
        entity.setAuthor(user.getId());
        return super.save(entity, paramToken, request);
    }

    }