package com.jsict.biz.controller;

import com.jsict.biz.model.WeddingPhoto;
import com.jsict.biz.service.WeddingPhotoService;
import com.jsict.framework.core.controller.AbstractGenericController;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Auto-Generated by UDP Generator
 *
 * 继承<code>com.jsict.framework.core.controller.AbstractGenericController</code>，封装通用的CRUD方法<br>
 * 可重写相关方法实现自定义CRUD的操作<br>
 * 可参考<a href="http://10.1.159.16/udp/unified_development_platform/blob/5.0-alpha/framework/src/main/java/com/jsict/framework/core/controller/AbstractGenericController.java">AbstractGenericController.java</a>
 */
@Api(value = "照片API", tags={"照片接口"})
@Controller
@RequestMapping("photo")
public class WeddingPhotoController extends
        AbstractGenericController<WeddingPhoto, String,
                WeddingPhoto> {

    @Autowired
    private WeddingPhotoService weddingPhotoService;

    @RequestMapping(
            value = {"/html"},
            method = {RequestMethod.POST},
            produces = {"application/json; charset=UTF-8"}
    )
    @ResponseBody
    @ApiOperation(value = "照片网页")
    public Map<String, Object> photoHtml(@RequestParam("album") String album) {
        Map<String, Object> result = new HashMap<>();
        List<WeddingPhoto> list = super.list(searchByAlbum(album));
        result.put("list", list);
        result.put("photoSort", weddingPhotoService.photoSort(list));
        return result;
    }

    private WeddingPhoto searchByAlbum(String album)
    {
        WeddingPhoto weddingPhoto = new WeddingPhoto();
        weddingPhoto.setAlbumSort(album);
        return weddingPhoto;
    }

}