package com.jsict.biz.dao;

import com.jsict.framework.core.dao.GenericDao;
import com.jsict.biz.model.Code;

/**
* Auto-Generated by UDP Generator
*/
public interface CodeDao extends GenericDao<Code, String> {
}