package com.jsict.biz.dao;

import com.jsict.framework.core.dao.GenericDao;
import com.jsict.biz.model.DataDictionary;
import com.jsict.framework.core.model.IDataDictionary;

import java.util.List;

/**
* Auto-Generated by UDP Generator
*/
public interface DataDictionaryDao extends GenericDao<DataDictionary, String> {

    /**
     * 获取数据字典表中指定分类的数据
     *
     * @param category
     * @return
     */
    List<IDataDictionary> getDataDictionary(String category);

    /**
     * 获取数据字典表中的数据字典
     *
     * @param category
     * @param code
     * @return
     */
    IDataDictionary getDataDictionaryByCode(String category, String code);


    /**
     * 获取指定数据字典表中的所有数据
     *
     * @param dictTable
     * @param dictCode
     * @param dictText
     * @return
     */
    List<IDataDictionary> getDataDictionary(String dictTable, String dictCode, String dictText);
}