package com.jsict.biz.dao;

import com.jsict.framework.core.dao.GenericDao;
import com.jsict.biz.model.Department;

/**
* Auto-Generated by UDP Generator
*/
public interface DepartmentDao extends GenericDao<Department, String> {
}