package com.jsict.biz.dao;

import com.jsict.framework.core.dao.GenericDao;
import com.jsict.biz.model.InformationContent;

/**
* Auto-Generated by UDP Generator
*/
public interface InformationContentDao extends GenericDao<InformationContent, String> {
}