package com.jsict.biz.dao;

import com.jsict.framework.core.dao.GenericDao;
import com.jsict.biz.model.Module;

/**
* Auto-Generated by UDP Generator
*/
public interface ModuleDao extends GenericDao<Module, String> {
}