package com.jsict.biz.dao;

import com.jsict.framework.core.dao.GenericDao;
import com.jsict.biz.model.MultiCode;


/**
* Auto-Generated by UDP Generator
*/
public interface MultiCodeDao extends GenericDao<MultiCode, String> {
}