package com.jsict.biz.dao;

import com.jsict.framework.core.dao.GenericDao;
import com.jsict.biz.model.Role;

/**
* Auto-Generated by UDP Generator
*/
public interface RoleDao extends GenericDao<Role, String> {
}