package com.jsict.biz.dao;

import com.jsict.biz.model.SensitiveWords;
import com.jsict.framework.core.dao.GenericDao;

/**
* Auto-Generated by UDP Generator
*/
public interface SensitiveWordsDao extends GenericDao<SensitiveWords, String> {
}