package com.jsict.biz.dao;

import com.jsict.framework.core.dao.GenericDao;
import com.jsict.biz.model.UdpPointPermission;

/**
* Auto-Generated by UDP Generator
*/
public interface UdpPointPermissionDao extends GenericDao<UdpPointPermission, String> {
}