package com.jsict.biz.dao;

import com.jsict.framework.core.dao.GenericDao;
import com.jsict.biz.model.User;

/**
* Auto-Generated by UDP Generator
*/
public interface UserDao extends GenericDao<User, String> {
}