package com.jsict.biz.dao;

import com.jsict.biz.model.WeddingPhoto;
import com.jsict.framework.core.dao.GenericDao;

/**
 * Auto-Generated by UDP Generator
 */
public interface WeddingPhotoDao extends GenericDao<WeddingPhoto, String> {
}